# Generated by Django 3.2.9 on 2021-12-31 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('money', models.FloatField(default=0)),
                ('xp', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('PA', 'Pre-Approval'), ('AC', 'Active'), ('RD', 'Retired or Dead')], default='PA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('discord', models.CharField(max_length=50)),
                ('downtime', models.PositiveIntegerField(default=0)),
                ('last_downtime_claim', models.DateTimeField()),
                ('spellcaster_hours', models.FloatField(default=0)),
                ('last_spellcaster_claim', models.DateTimeField()),
                ('isViceroy', models.BooleanField(default=False)),
                ('viceroy_tokens', models.PositiveIntegerField(default=0)),
                ('isGM', models.BooleanField(default=False)),
                ('gm_tokens', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_verified', models.BooleanField()),
                ('buyer_verified', models.BooleanField()),
                ('money_amount', models.FloatField()),
                ('what_was_purchased', models.TextField(max_length=1000)),
                ('other_stipulations', models.TextField(max_length=1000)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_of_buyer', to='resource_tracker.player')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_of_seller', to='resource_tracker.player')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_of_creditor', to='resource_tracker.character')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_of_debtor', to='resource_tracker.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_tracker.player'),
        ),
    ]
