# Generated by Django 3.2.9 on 2021-12-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_downtime_claim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_spellcaster_claim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
