# Generated by Django 3.2.9 on 2021-12-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='role',
        ),
        migrations.AddField(
            model_name='player',
            name='isGM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='isViceroy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='downtime',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='spellcaster_hours',
            field=models.FloatField(default=0),
        ),
    ]
