# Generated by Django 3.2.9 on 2021-12-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0002_auto_20211231_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
