# Generated by Django 3.2.9 on 2021-12-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0004_remove_player_server_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='money',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('PA', 'Pre-Approval'), ('AC', 'Active'), ('RD', 'Retired or Dead')], default='PA', max_length=2),
        ),
    ]
