# Generated by Django 3.2.9 on 2022-01-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0004_auto_20220109_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
