# Generated by Django 3.2.9 on 2021-12-23 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0006_auto_20211223_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='approved',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
