# Generated by Django 3.2.9 on 2021-12-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0007_auto_20211223_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='approved',
            field=models.DateTimeField(null=True),
        ),
    ]
