# Generated by Django 3.2.9 on 2021-12-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0008_alter_character_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=500)),
            ],
        ),
    ]
