# Generated by Django 3.2.9 on 2021-12-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0010_character_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gm_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='viceroy_gp',
            field=models.FloatField(default=0),
        ),
    ]
