# Generated by Django 3.2.9 on 2021-12-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0011_auto_20211223_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='xp',
            field=models.FloatField(default=0),
        ),
    ]
