# Generated by Django 3.2.9 on 2021-12-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0012_alter_character_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
