# Generated by Django 3.2.9 on 2021-12-24 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0014_auto_20211223_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='spellcaster_hours',
        ),
    ]
