# Generated by Django 3.2.9 on 2021-12-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0015_remove_player_spellcaster_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='spellcaster_hours',
            field=models.FloatField(default=0),
        ),
    ]
