# Generated by Django 3.2.9 on 2021-12-24 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0016_player_spellcaster_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_downtime_claim',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_spellcaster_claim',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
